tests/test_history_server.py
yarn_api_client/__init__.py
yarn_api_client/base.py
yarn_api_client/history_server.py

Use attempts/xxx to access attempt info in Hadoop 2.6
I do not have currently older Hadoop version to check

Fix History REST API

---

yarn_api_client/resource_manager.py

The recently introduced cluster_application_kill() method was erroneously
calling `self.put()` to issue the status change to `KILLED`.  This resulted
in an AttributeError exception:
```
''ResourceManager' object has no attribute 'put''
```
in client code.
The base class issues put calls, via its `update()` method.  Once updated,
application kill requests succeed.

Fix cluster_application_kill method

---

yarn_api_client/hadoop_conf.py

Hello @toidi 
When setting `CONF_DIR` in `yarn_api_client/hadoop_conf.py` it would be nice to check for conf dir overrides defined via the `HADOOP_CONF_DIR` env var. Comes in handy when working with hadoop clients defined in non standard paths.
Impact should be super minimal. Appreciate the consideration.
Cheers!

check for HADOOP_CONF_DIR env var

---

tests/test_base.py
tests/test_hadoop_conf.py
tests/test_history_server.py
tests/test_node_manager.py
tests/test_resource_manager.py
yarn_api_client/__init__.py
yarn_api_client/application_master.py
yarn_api_client/base.py
yarn_api_client/hadoop_conf.py
yarn_api_client/history_server.py
yarn_api_client/main.py
yarn_api_client/node_manager.py
yarn_api_client/resource_manager.py

This is cleanup based of flake8 and pylint recommendations + corrections to make implementation more generic (for future extensibility of support POST/PUT/DELETE calls)
Update: also added new-application api to fix #30

Code cleanup/refactoring

---

tests/test_hadoop_conf.py
yarn_api_client/hadoop_conf.py
yarn_api_client/resource_manager.py

Alternate address and port parameters can now be passed to the ResourceManager
constructor.  ~This has been facilitated via a keyword args dict (kwargs) to 
accommodate future parameters.~  If both `address` and `alt_address` are provided,
`address` and `port` will be used to determine if the RM is active.  If not, then
`alt_address` and `alt_port` will be used.  If the latter is active, the address
and port member variables are reset to reflect the alternates.
Also added method `get_active_host_port()` to return the address, port tuple currently
in use for the ResourceManager instance.  This is helpful to clients in cases where
the address was None or HA is configured.
Fixes: #9 
EDIT: Removed use of `kwargs` per review comment.

Add support for handling multiple RMs sans Hadoop config

---

yarn_api_client/base.py

POST api is responding with response code 202 instead of 200
https://hadoop.apache.org/docs/r2.7.3/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html#Cluster_New_Application_API

Fix POST response code API handling

---

tests/test_resource_manager.py
yarn_api_client/resource_manager.py

The params dict was being passed as a kwargs parameter (`**params`)
rather than as a kwarg itself (e.g., `params=params`).  As a result,
the change in the `request()` method was passing each of the parameters
intended for the YARN RM as keyword arguments to the `requests()` method
itself.  This produced the following error on such requests...
```
<class 'TypeError'> - 'request() got an unexpected keyword argument
'startedTimeBegin'
```
resulting in failures in `0.3.4`.

[HOTFIX] Fix how params dict is passed to request()

---

tests/test_hadoop_conf.py
tests/test_resource_manager.py
yarn_api_client/base.py
yarn_api_client/hadoop_conf.py
yarn_api_client/resource_manager.py

The current implementation does not honor the configured HTTP policy within `yarn-site.xml`.  As a result, if the HTTP policy reflects `HTTPS_ONLY`, the ResourceManager object will fail.  These changes allow for installations to leverage HTTPS **when using the default configuration**.  That is, HTTPS is still not supported if an `address` is provided to `ResourceManager` due to the fact that the protocol is not  conveyed in the request.  
Once PR #34 is merged (requires a new release), we can then interrogate the protocol to determine that HTTPS has been requested.  (Note: these changes will likely be warranted following #34's merge.)

Honor http policy

---

tests/test_resource_manager.py
yarn_api_client/resource_manager.py

This is another batch of fixes to cover some of my findings in https://github.com/toidi/hadoop-yarn-api-python-client/pull/34#issuecomment-532006608
(mainly points 1, 3, 4) + some small code adjustments to point out ALPHA marked APIs in ResourceManager documentation.
+
This should cover fix for #8 and effectively include #3

ResourceManager API fixes for latest spec

---

yarn_api_client/base.py
yarn_api_client/hadoop_conf.py

Port field is an int so composition into strings requires a cast.
Pass explicit host and port to HTTPConnection initializers since
it doesn't appear to parse out the port number when a path is also
included.
Fixes #45

Fix Uri object and usage issues

---

tests/test_resource_manager.py
yarn_api_client/base.py
yarn_api_client/resource_manager.py

This PR is to cover missing APIs for RM mentioned in https://github.com/toidi/hadoop-yarn-api-python-client/pull/34#issuecomment-532006608
Some gaps left still, not sure if it worth merging before filling those.
It's only covering RM, not other components (that might still have some API off)

Add missing RM apis

---

README.md
yarn_api_client/__init__.py

The `v1.0.0` tag will be applied to the appropriate commit (https://github.com/toidi/hadoop-yarn-api-python-client/commit/3e84724c400b3853a136f4cc18ea90fbac816ed5) once merged to master.

Release 1.0

---

setup.py
yarn_api_client/__init__.py

Found that the conversion of `README.rst` to `README.md` breaks pushes to pypi.org where `setup.py` uses it for the `long_description`.  This change specifies that `text/markdown` be the expected content type for `long_description`.  (I've also already posted the build to pypi to confirm. :smile:)

Release 1.0 (Redo)

---

tests/test_application_master.py
tests/test_hadoop_conf.py
tests/test_resource_manager.py
yarn_api_client/application_master.py
yarn_api_client/hadoop_conf.py
yarn_api_client/resource_manager.py

This is to fix #57 
One thing I'm still not sure about is next:
https://github.com/dimon222/hadoop-yarn-api-python-client/blob/82022a1574c6134ade132736ef64d642053b13dc/yarn_api_client/hadoop_conf.py#L52-L57
Should we validate for 401 and throw exception for auth immediately or its valid scenario when we should return just False?

Pass auth to Active RM check

---

README.md

Since we lost control over the older build page and docs don't really represent there proper latest documentation, I've created new project for this with slightly different name.
This will now point to project that builds proper documentation page properly
PS: i've also added @lresende and @kevin-bates as maintainers so that you guys can setup webhooks in github for this project

ReadTheDocs new project link

---

.travis.yml
setup.py
tox.ini

I noticed that we are kind of out of date with recent python releases, so adding them to test coverage... Also remove 2.6 since we don't test against it, and 2.x tree is EOL anyway next year.

Add test suites for new python versions

---

docs/base.rst
docs/index.rst
yarn_api_client/application_master.py
yarn_api_client/base.py
yarn_api_client/history_server.py
yarn_api_client/node_manager.py
yarn_api_client/resource_manager.py

I noticed some graphical issues due to incorrect formatting of some classes, so this PR covers:
1. All the graphical typos with newlines/multiline descriptions that I noticed
2. New link to Response object description (since we need to explain user how to work with response data object)
3. Improvements based of warnings/recommendations of sphinx
4. New formatting for "alpha" marked features of hadoop since our asterisk way didn't work properly for RST formatting generation

Clean documentation

---

tests/test_base.py
tests/test_resource_manager.py
yarn_api_client/base.py

There was typo in condition (`and` vs `or`) which could cause side effects. This PR fixes it. + There was rare scenario when url has http/https in the beginning of domain. This PR will check proper part of url with `://`.
+
To reduce amount of confusion/random regressions I've added tests for url parsing.
PS: @lresende @kevin-bates The patch for `urlparse` was backported to earlier pythons in sub version (for ex. 3.7.6), so unfortunately this #71 won't completely save us (https://github.com/toidi/hadoop-yarn-api-python-client/issues/69#issuecomment-569135622) . As soon as somebody updates to new version of python, they might get in issues when they use this specific kind of URL `test.com:1234` (with no schema specified). To mitigate this, we have to make sure we cover corner cases - this …

Fix HTTPS uri parsing and add tests for it

---

.travis.yml

The recent Python (3.8.x) releases has been causing some regressions in our code, so this would enable us to learn about those faster.

Enable builds on Python 3.8-dev pre-releases

---

tests/test_application_master.py
tests/test_resource_manager.py
yarn_api_client/application_master.py
yarn_api_client/resource_manager.py

Fix json body request apis

---

yarn_api_client/base.py

Application submission via the REST API does not return a response
body.  This updates ensures that an empty dictionary is returned
in such cases.
Fixes: #76

Handle responses with empty content

---

tests/test_base.py
yarn_api_client/application_master.py
yarn_api_client/base.py
yarn_api_client/hadoop_conf.py
yarn_api_client/history_server.py
yarn_api_client/main.py
yarn_api_client/node_manager.py
yarn_api_client/resource_manager.py

This change enables a logger for each module of yarn-api-client.
By default, nothing will be logged unless the calling application has
configured logging.  Once configured, entries will be logged relative
to the configured log level. The calling application is also responsible
or specifying the appropriate log formats, etc.
An accessor method, get_logger(logger_name), has been created in case we
need to add configuration for the loggers.  In those cases, we'd probably
configure the logger "yarn_api_client", so that each of the submodule
loggers would inherit from that logger.  Likewise, applications can
configure "yarn_api_client" themselves and those changes will be picked
up by the individual loggers.
The previous INFO log statement has been changed to DEBUG and I've
added timing …

Enable logging for all components, remove print statements

---

tests/test_hadoop_conf.py
yarn_api_client/hadoop_conf.py

I faced with the issue "Python request: No connection adapters were found for..." when I passed yarn-site.xml file and called the constructor of the class ResourceManager without any arguments.
According to the Yarn documentation https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/ResourceManagerHA.html
the protocol scheme isn't stored in the values of parameters yarn.resourcemanager.webapp.address.rm-id & yarn.resourcemanager.webapp.https.address.rm-id

The protocol scheme was added in the phase of finding the active RM.

---

.travis.yml
itests/integration_test_resource_manager.py
setup.cfg
setup.py
tox.ini
yarn_api_client/base.py

These changes remove support for Python 2.7 since our builds are now breaking (#85).  This does not preclude the use of Hadoop YARN 2.7-based systems, just that the yarn-client app must be invoked from Python 3.5+.

Remove support for Python 2.7

---

README.md

PS: same problem with coveralls, but somebody with higher access privleges have to create new repo sync on Coveralls (not visible for me on their site).

Update travis badge link

---

README.md

This should be more straightforward one-liner for git install + update link to latest CODAIT repo (instead of old one)

One-line pip install from git

---

tox.ini

Looks like an updated `cryptography` release (pulled in by `requests-kerberos`) isn't installable without a rust compiler on python 3.6.  This change caps the `cryptography` release to `<=3.2.2` (which doesn't introduce that requirement) for CI.

Fix 3.6 build failures

---

yarn_api_client/hadoop_conf.py

When both defined then `YARN_CONF_DIR` should have priority as it is more
specific.

Support YARN_CONF_DIR along with HADOOP_CONF_DIR

---

README.md
setup.py
tox.ini
yarn_api_client/__init__.py

I've rollbacked to tree 1.0.3 because this release is not as significant to bump entire major version to 2.0.0

Cleanup for release 1.0.3
